### ISSUE TITLE
IllegalArgumentException: 1642 is not a valid offset for file 

### ISSUE THREAD

**Issue by SilkSama** [arturbosch/sonar-kotlin#95]
Hi,
I'm on sonarqube 6.7.7-community and I have an error with your plugin (0.6.0).

`Caused by: java.lang.IllegalArgumentException: 1642 is not a valid offset for file ...... Max offset is 1636
        at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:291)
        at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:285)
        at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:83)
        ... 110 more
`

Thank you in advance for your help.

**Comment by SilkSama** [comment]
Ok, if I disable Formatting rule everything is ok.

**Comment by arturbosch** [comment]
Hey, glad it worked out for you.
Could be please write down for others which rule you had to disable to make it work?
